trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'/terraform/
    contents: '**/$(BuildConfiguration)/**/?(*.tf)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'terra'