# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  displayName: Instalação Terraform
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  displayName: terraform init
  enabled: true
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/env/dev'
    backendServiceAWS: 'terraform-mack-app-us-east-1'
    backendAWSBucketName: 'gabu-terraform-bucket-mack-us-east-1'
    backendAWSKey: 'tf/terraform.ftstate'
- task: TerraformTaskV3@3
  displayName: terraform plan
  enabled: true
  inputs:
    provider: 'aws'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/env/dev'
    environmentServiceNameAWS: 'terraform-mack-app-us-east-1'
- task: TerraformTaskV3@3
  displayName: terraform apply
  enabled: true
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/env/dev'
    environmentServiceNameAWS: 'terraform-mack-app-us-east-1'
- task: TerraformTaskV3@3
  displayName: terraform destroy
  enabled: false
  inputs:
    provider: 'aws'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/env/dev'
    environmentServiceNameAWS: 'terraform-mack-app-us-east-1'